site_name: Flask-WaffleConf
theme: readthedocs
pages:
    - Home: index.md
    - Quickstart: quickstart.md
    - Multiprocess deployments: multiproc.md
    - Configuration: configuration.md
    - API reference:
        - 'Model': api/model.md
        - 'Store': api/store.md
        - 'WaffleConf': api/waffleconf.md
        - 'Views': api/views.md
        - 'Utils': api/util.md
